/*
 * Created: 2025/3/8
 * Author:  hineven
 * See LICENSE for licensing.
 */
#include <ranges>
#include <utility>
#include <locale>

#include <xxhash.h>
#include "rdg/rdg_shader.h"

#include <codecvt>

#include "rhi/rhi.h"
#include "rhi/rhi_pipeline.h"
#include "core/infra.h"

MI_NAMESPACE_BEGIN

size_t RDGShaderInitializationInfo::GetHash() const {
    size_t final_hash = 0;
    for (const auto & macro : macros) {
        final_hash ^= XXH64(macro.c_str(), macro.size(), 12312321);
    }
    return final_hash;
}

bool RDGShaderParamStructInfo::CanBeRenderpass () const {
    for (auto & member : cpp_members) {
        if (member.type != RHIParamType::kRenderTarget) return false;
    }
    return true;
}

RDGShaderHash &RDGShaderHash::AddUnordered(const char *marker, uint64_t v) {
    uint64_t hash = XXH64(marker, strlen(marker), v);
    value ^= hash;
    return * this;
}


RDGShader::RDGShader (const RDGShaderClassRegistry * class_registry) : class_registry_(class_registry) {

}

RDGShader::~RDGShader () {

}

static std::string LoadFile(const std::string & path) {
    auto reader = GetInfra().RIO_Open(path, MIInfraResourceHintType::kShaderSource);
    if (!reader) {
        MI_LOG(MIInfraLogType::kError, "Failed to open resource: {}", path);
        return {};
    }
    auto size = reader->GetSize();
    std::string content(size, '\0');
    reader->ReadBlob(0, size, content.data());
    return content;
}

bool RDGShader::CheckShaderReflection(RHIShader * shader, const RDGShaderParamStructAndSizeInfo &info) {
    // Firstly, export uniform buffers from cpp shader param struct reflection
    TOneTimeLinearAllocator<> aloc;

    // Quick compare with hash values for the referenced structs
    bool passed_checking = true;
    auto & shader_reflected_uniform_buffers = shader->GetUniformBufferDesc();
    bool has_bindless = shader->HasBindlessResources();

    // Look for the autogenerated '$Globals' uniform buffer. (which should not be present)
    {
        bool flag = false;
        for (int j = 0; j < (int)shader_reflected_uniform_buffers.size(); ++j) {
            if (shader_reflected_uniform_buffers[j].name == "$Globals") {
                flag = true;
                break;
            }
        }
        if (flag) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' - Global uniform buffer is not supported. Use something like 'ConstantBuffer<UniformBufferStruct> UB;' instead.",
                   class_registry_->source_location);
            passed_checking = false;
        }
    }

    if ((int)shader_reflected_uniform_buffers.size() - has_bindless > info.uniform_buffers_.size()) {
        // Shader is requesting for more uniform buffers than C++ has defined, find and log the missing ones
        for (const auto& shader_ub : shader_reflected_uniform_buffers) {
            bool found = false;
            for (const auto& cpp_ub : info.uniform_buffers_) {
                if (shader_ub.name == cpp_ub.info->name) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' - Uniform buffer '{}' is defined in shader but not found in C++",
                       class_registry_->source_location, shader_ub.name);
                passed_checking = false;
            }
        }
    }
    // Check and remap referenced uniform buffers
    cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer].resize(info.uniform_buffers_.size(), UINT32_MAX);
    for (auto const & [i, e] : info.uniform_buffers_ | std::views::enumerate) {
        // find corresponding uniform buffer in shader reflection
        int shader_ub_idx = -1;
        for (int j = 0; j < (int)shader_reflected_uniform_buffers.size(); ++j) {
            if (shader_reflected_uniform_buffers[j].name == e.info->name) {
                shader_ub_idx = j;
                break;
            }
        }
        if (shader_ub_idx == -1) {
            // No need to pop up warnings. There may be culled unused UBs in shader reflection.
            // MI_LOG(MIInfraLogType::kWarning,
            //        "Shader '{}' - Uniform buffer '{}' is defined in C++ but not found in shader",
            //        class_registry_->source_location, e.info->name);
            // passed_checking = false;
        } else {
            // 25.5.19: Deep reflection is removed for uniform buffer structs.
            // It is up to the user for maintaining consistency between C++ and shaders.
            // Now we simply check if the sizes mismatches.
            if (shader_reflected_uniform_buffers[shader_ub_idx].array_size > 0) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' - Array '{}' of uniform buffers of length {} is not supported. (Any UB array is not supported).",
                       class_registry_->source_location, e.info->name, shader_reflected_uniform_buffers[shader_ub_idx].array_size);
                passed_checking = false;
            }
            if (shader_reflected_uniform_buffers[shader_ub_idx].size != e.info->size) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' - Uniform buffer '{}' has size mismatch between C++ and shader."
                       "Shader size: {}, C++ size: {}.",
                       class_registry_->source_location, e.info->name, shader_reflected_uniform_buffers[shader_ub_idx].size, e.info->size);
                passed_checking = false;
            }
        }
    }

    // Check shader resources other than uniform buffers. They are easier to check.

    auto FindIndex = [&](std::span<RDGShaderParameterLocation> resources, const std::string & name) -> int {
        for (int i = 0; i < (int)resources.size(); ++i) {
            if (resources[i].info->name == name) {
                return i;
            }
        }
        return -1;
    };

    // Check storage buffers
    cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer].resize(info.storage_buffers_.size(), UINT32_MAX);
    for (const auto& sb : shader->GetStorageBufferDesc()) {
        int index = FindIndex(info.storage_buffers_, sb.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' uses storage buffer '{}' which is not defined in shader parameters",
                   class_registry_->source_location, sb.name);
            passed_checking = false;
        } else {
            auto & member = *info.storage_buffers_[index].info;
            if (member.access_flags != sb.access_flags) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' defines '{}' as storage buffer but parameter has incompatible access flags."
                       "Shader flags: {}, Parameter flags: {}",
                       class_registry_->source_location, sb.name, ToString(sb.access_flags), ToString(member.access_flags));
                passed_checking = false;
            }
        }
    }

    // Check UAV textures
    for (const auto& uav : shader->GetUAVDesc()) {
        int index = FindIndex(info.uavs_, uav.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' uses UAV texture '{}' which is not defined in shader parameters",
                   class_registry_->source_location, uav.name);
            passed_checking = false;
        } else {
            auto & member = *info.uavs_[index].info;
            if (member.type != RHIParamType::kUAVTexture && member.type != RHIParamType::kUAVTextureArray) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' defines '{}' as UAV texture but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, uav.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }
    // Check SRV textures
    for (const auto& srv : shader->GetSRVDesc()) {
        int index = FindIndex(info.srvs_, srv.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' uses SRV texture '{}' which is not defined in shader parameters",
                   class_registry_->source_location, srv.name);
            passed_checking = false;
        } else {
            auto & member = *info.srvs_[index].info;
            if (member.type != RHIParamType::kSRVTexture && member.type != RHIParamType::kSRVTextureArray) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' defines '{}' as SRV texture but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, srv.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check samplers
    for (const auto& sampler : shader->GetSamplerDesc()) {
        int index = FindIndex(info.samplers_, sampler.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' uses sampler '{}' which is not defined in shader parameters",
                   class_registry_->source_location, sampler.name);
            passed_checking = false;
        } else {
            auto & member = *info.samplers_[index].info;
            if (member.type != RHIParamType::kSampler) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' defines '{}' as sampler but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, sampler.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check acceleration structures
    for (const auto& as : shader->GetAccelerationStructureDesc()) {
        int index = FindIndex(info.acceleration_structures_, as.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' uses acceleration structure '{}' which is not defined in shader parameters",
                   class_registry_->source_location, as.name);
            passed_checking = false;
        } else {
            auto & member = *info.acceleration_structures_[index].info;
            if (member.type != RHIParamType::kAccelerationStructure) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}' defines '{}' as acceleration structure but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, as.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check vertex attributes
    for (const auto& vb : shader->GetVertexInputDesc()) {
        int index = info.GetCppMemberIndex(vb.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                "Shader '{}' uses vertex attribute '{}' (location {}) which is not defined in shader parameters",
                class_registry_->source_location, vb.name, vb.location);
            passed_checking = false;
            // Find the vertex attribute with corresponding location
            for (auto & member : info.cpp_members) {
                if (member.type == RHIParamType::kVertexAttribute
                && member.cpp_extra.vertex_attribute_info->attribute_index == vb.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "The declared vertex attribute with corresponding location is {}",
                        member.name);
                    break;
                }
            }
        } else {
            auto & member = info.cpp_members[index];
            if (member.type != RHIParamType::kVertexAttribute) {
                MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}' defines '{}' as vertex attribute but parameter has incompatible type."
                        "Parameter type: {}",
                        class_registry_->source_location, vb.name, ToString(member.type));
                passed_checking = false;
            } else {
                if (member.cpp_extra.vertex_attribute_info->attribute_index != vb.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}' defines '{}' as vertex attribute but parameter has incompatible location."
                        "Parameter location: {}, Shader location: {}",
                        class_registry_->source_location, vb.name, member.cpp_extra.vertex_attribute_info->attribute_index, vb.location);
                    passed_checking = false;
                }
                if (member.cpp_extra.vertex_attribute_info->format != vb.format) {
                    MI_LOG(MIInfraLogType::kWarning,
                            "Shader '{}' defines '{}' as vertex attribute but parameter has incompatible format."
                            "Parameter format: {}, Shader format: {}",
                            class_registry_->source_location, vb.name, ToString(member.cpp_extra.vertex_attribute_info->format), ToString(vb.format));
                    passed_checking = false;
                }
            }
        }
    }

    // Check fragment outputs (RenderTarget vs fragment output reflected from SPIR-V, check format compatibility)
    // (Names can be different, but the location and format must match)
    if (shader->GetFragmentOutputDesc().size()) {
        if (!info.render_targets_.size()) {
            MI_LOG(MIInfraLogType::kWarning, "Shader {} has fragment outputs but no render target is specified in C++.", class_registry_->source_location);
            passed_checking = false;
        } else {
            if (info.render_targets_.size() < shader->GetFragmentOutputDesc().size()) {
                MI_LOG(MIInfraLogType::kWarning,
                    "Shader {} has {} fragment outputs but only {} is specified in C++, which is insufficient.",
                    class_registry_->source_location, shader->GetFragmentOutputDesc().size(), info.render_targets_.size());
                passed_checking = false;
            }
        }
    }
    for (const auto & [i, output] : std::views::enumerate(shader->GetFragmentOutputDesc())) {
        int index = (int)i;
        if (index < info.render_targets_.size()) {
            auto & member = *info.render_targets_[index].info;
            if (member.type != RHIParamType::kRenderTarget) {
                MI_LOG(MIInfraLogType::kWarning,
                    "Shader '{}' defines '{}' as fragment output but parameter has incompatible type."
                    "Parameter type: {}",
                    class_registry_->source_location, output.name, ToString(member.type));
                passed_checking = false;
            } else {
                if (member.cpp_extra.render_targets_info->target_index != output.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}' defines '{}' as fragment output but parameter has incompatible location."
                        "Parameter location: {}, Shader location: {}",
                        class_registry_->source_location, output.name, member.cpp_extra.render_targets_info->target_index, output.location);
                    passed_checking = false;
                }
                if (!RHIIsOutputCompatiablePixelFormat(output.format, member.cpp_extra.render_targets_info->format)) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}' defines '{}' as fragment output but parameter has incompatible format."
                        "Parameter format: {}, Shader format: {}",
                        class_registry_->source_location, output.name, ToString(member.cpp_extra.render_targets_info->format), ToString(output.format));
                    passed_checking = false;
                }
            }
        }
    }

    // TODO check immutable samplers, ...
    return passed_checking;
}

std::vector<std::string> RDGShader::GetExtraCompilerOptions(const RDGShaderInitializationInfo & ini) const {
    std::vector<std::string> extra_options;
    auto macros = class_registry_->GetShaderDefaultMacros();
    for (const auto & macro : macros) {
        extra_options.emplace_back("-D" + macro);
    }
    for (const auto & extra_macro : ini.macros) {
        extra_options.emplace_back("-D" + extra_macro);
    }
    return extra_options;
}

void RDGShader::RemapResourceIndexToRHIResourceSlots() {
    // Clear the previous bindings
    for (auto & e : cpp_resource_index_to_slot_) e.clear();
    assert(IsValid() && "Only with an assembled pipeline can we remap bindings");
    auto & info = *class_registry_->GetShaderParamStructInfo();
    RHIPipeline * pipeline = nullptr;
    if (class_registry_->type == RHIPipelineType::kGraphics) {
        pipeline = graphics_pipeline_.Raw();
    } else if (class_registry_->type == RHIPipelineType::kCompute) {
        pipeline = compute_pipeline_.Raw();
    } else {
        assert(false);
        return;
    }
    auto FindSlotIndex = [&] <typename T> (const std::string & name, T & list) {
        for (int i = 0; i < (int)list.size(); ++i) {
            if (list[i].name == name) {
                return i;
            }
        }
        return -1;
    };
    // Remap uniform buffers
    {
        auto & ub = pipeline->GetUniformBufferDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer].resize(info.uniform_buffers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.uniform_buffers_)) {
            auto index = FindSlotIndex(e.info->name, ub);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer][i] = index;
            }
            // Potentially there are UBs declared in cpp but not present in shaders. Simply omit that case.
        }
    }
    // Remap storage buffers
    {
        auto & sb = pipeline->GetStorageBufferDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer].resize(info.storage_buffers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.storage_buffers_)) {
            auto index = FindSlotIndex(e.info->name, sb);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer][i] = index;
            }
        }
    }
    // Remap uavs
    {
        auto & uavs = pipeline->GetUAVDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUAVTexture].resize(info.uavs_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.uavs_)) {
            auto index = FindSlotIndex(e.info->name, uavs);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUAVTexture][i] = index;
            }
        }
    }
    // Remap srvs
    {
        auto & srvs = pipeline->GetSRVDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSRVTexture].resize(info.srvs_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.srvs_)) {
            auto index = FindSlotIndex(e.info->name, srvs);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSRVTexture][i] = index;
            }
        }
    }
    // Remap samplers
    {
        auto & samplers = pipeline->GetSamplerDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSampler].resize(info.samplers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.samplers_)) {
            auto index = FindSlotIndex(e.info->name, samplers);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSampler][i] = index;
            }
        }
    }
    // Remap as
    {
        auto & as = pipeline->GetAccelerationStructureDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kAccelerationStructure].resize(info.acceleration_structures_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.acceleration_structures_)) {
            auto index = FindSlotIndex(e.info->name, as);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kAccelerationStructure][i] = index;
            }
        }
    }
}



std::string RDGShader::LoadSource () const {
    // Firstly, load the source code from the source location
    auto source_code = LoadFile(class_registry_->source_location);
    return source_code;
}

// Localization support from C++ standard is incomplete. Resorting to codecvt
#pragma warning(push)
#pragma warning(disable : 4996)
static std::string wstring_to_utf8(std::wstring const& str)
{
    std::wstring_convert<std::conditional_t<
          sizeof(wchar_t) == 4,
          std::codecvt_utf8<wchar_t>,
          std::codecvt_utf8_utf16<wchar_t>>> converter;
    return converter.to_bytes(str);
}
#pragma warning(pop)

RDGShaderHash RDGShader::ComputeShaderHash() const {
    auto source_code = LoadSource();
    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "Failed to load shader source: {}", class_registry_->source_location);
        return {};
    }
    std::vector<std::string> extra_options = GetExtraCompilerOptions(ini_);

    RDGShaderHash shader_hash {};

    if (class_registry_->type == RHIPipelineType::kCompute) {
        bool is_valid {false};
        auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
            class_registry_->source_location, extra_options, is_valid
        );
        if (is_valid) shader_hash.AddUnordered("ComputeShader", result);
    }

    if (class_registry_->type == RHIPipelineType::kGraphics) {
        if (!class_registry_->vertex_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("VertexShader", result);
        }
        if (!class_registry_->fragment_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("FragmentShader", result);
        }
    }
    if (shader_hash.value == 0) {
        MI_LOG(MIInfraLogType::kError, "Failed to compute shader hash: {}", class_registry_->source_location);
        return {};
    }
    return shader_hash;
}


bool RDGShader::RecompileShaders(const std::string & source_code, const RDGShaderInitializationInfo & ini) {
    // Re-compile the shader
    shaders_ = {};
    shader_hash_.Reset();

    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "Empty shader source: {}", class_registry_->source_location);
        return false;
    }
    // Reflect shader struct param info
    const RDGShaderParamStructAndSizeInfo & param_info = *class_registry_->GetShaderParamStructInfo();

    // Compile the shader and create RHI shaders
    std::string errmsg;
    auto absolute_path = GetInfra().TranslateResPathToFilePath(class_registry_->source_location);
    auto absolute_path_string = absolute_path.string();
    std::wstring source_location_wstr(absolute_path_string.begin(), absolute_path_string.end());

    // Stack macros
    std::vector<std::string> extra_options = GetExtraCompilerOptions(ini);

    if(class_registry_->type == RHIPipelineType::kCompute) {
        uint64_t cs_hash = 0;
        std::wstring out_command;
        auto result = GetInfra().CompileHLSLToSPIRV(
                source_location_wstr.c_str(), std::string(class_registry_->compute_entry_), "cs_6_6",
                std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &cs_hash
        );
        if (result.empty()) {
            MI_LOG(MIInfraLogType::kError, "Failed to compile shader: {}", errmsg);
            MI_LOG(MIInfraLogType::kError, "Imaginary compile command: {}", wstring_to_utf8(out_command));
            return false;
        }
        shader_hash_.AddUnordered("ComputeShader", cs_hash);
        // Create the compute shader
        auto bytecode_span = std::span(reinterpret_cast<const std::byte *>(result.data()), result.size() * sizeof(uint32_t));
        auto shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kCompute, class_registry_->compute_entry_,
                RHIShaderIRType::kSPIRV, bytecode_span
        );
        if (!shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Compute shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.compute = shader;
    }
    if(class_registry_->type == RHIPipelineType::kGraphics) {
        std::vector<uint32_t> vs_result, fs_result;
        // For graphics pipeline, we need to compile vertex and fragment shaders
        // First compile vertex shader
        {
            uint64_t vs_hash = 0;
            std::wstring out_command;
            vs_result = GetInfra().CompileHLSLToSPIRV(
                    source_location_wstr.c_str(), std::string(class_registry_->vertex_entry_), "vs_6_3",
                    std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &vs_hash
            );
            if (vs_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile vertex shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Imaginary compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("VertexShader", vs_hash);
        }

        {
            uint64_t fs_hash = 0;
            std::wstring out_command;
            // Then compile fragment shader
            fs_result = GetInfra().CompileHLSLToSPIRV(
                    source_location_wstr.c_str(), std::string(class_registry_->fragment_entry_), "ps_6_3",
                    std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &fs_hash
            );
            if (fs_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile fragment shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Imaginary compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("FragmentShader", fs_hash);
        }

        // Create the vertex shader
        auto vs_bytecode_span = std::span(reinterpret_cast<const std::byte*>(vs_result.data()), vs_result.size() * sizeof(uint32_t));
        auto vertex_shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kVertex, class_registry_->vertex_entry_,
                RHIShaderIRType::kSPIRV, vs_bytecode_span
        );
        if (!vertex_shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create vertex shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(vertex_shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Vertex shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.vertex = vertex_shader;

        // Create the fragment shader
        auto fs_bytecode_span = std::span(reinterpret_cast<const std::byte*>(fs_result.data()), fs_result.size() * sizeof(uint32_t));
        auto fragment_shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kFragment, class_registry_->fragment_entry_,
                RHIShaderIRType::kSPIRV, fs_bytecode_span
        );
        if (!fragment_shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create fragment shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(fragment_shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Fragment shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.fragment = fragment_shader;
    }
    return true;
}

bool RDGShader::Recompile(RDGShaderInitializationInfo ini) {

    // Clear legacy resources
    graphics_pipeline_ = {};
    compute_pipeline_ = {};
    shaders_ = {};
    is_valid_ = false;

    auto source_code = LoadSource();
    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "Failed to load shader source: {}", class_registry_->source_location);
        return false;
    }
    if (!RecompileShaders(source_code, ini)) return false;

    auto pipeline_config = class_registry_->GetShaderPipelineConfig();

    // Assemble the pipeline
    if (class_registry_->type == RHIPipelineType::kCompute) {
        auto pipeline = RHI::Get().CreateComputePipeline(
            shaders_.compute.Raw(), class_registry_->name.c_str()
        );
        if (!pipeline) {
            MI_LOG(MIInfraLogType::kError, "Failed to create compute pipeline");
            return false;
        }
        compute_pipeline_ = pipeline;
    }
    if (class_registry_->type == RHIPipelineType::kGraphics) {
        RHIGraphicsPipelineDesc desc {};
        desc.stages.vertex_shader = shaders_.vertex.Raw();
        desc.stages.fragment_shader = shaders_.fragment.Raw();
        auto vertex_inputs = shaders_.vertex->GetVertexInputDesc();
        std::vector<RHIVertexInputBindingDesc> rhi_bindings;
        std::vector<RHIVertexInputAttributeDesc> rhi_attributes;
        // Gather vertex input configurations from shader param struct info
        auto params = class_registry_->GetShaderParamStructInfo();
        for (auto & e : params->cpp_members) {
            if (e.type == RHIParamType::kVertexBuffer) {
                auto input = e.cpp_extra.vertex_buffer_info;
                // TODO support more input rates
                rhi_bindings.emplace_back(input->index, input->stride, RHIVertexInputRateType::kVertex);
            }
            if (e.type == RHIParamType::kVertexAttribute) {
                auto attr = e.cpp_extra.vertex_attribute_info;
                rhi_attributes.emplace_back(attr->attribute_index, attr->buffer_index, attr->format, attr->offset);
            }
        }
        desc.vertex_input.vertex_buffers = rhi_bindings;
        desc.vertex_input.vertex_attributes = rhi_attributes;
        desc.topology = pipeline_config.topology;


        auto fragment_outputs = shaders_.fragment->GetFragmentOutputDesc();
        std::vector<RHIColorAttachmentDesc> color_attachments;
        RHIDepthStencilAttachmentDesc depth_stencil {};
        // Gather color attachment configurations from shader param struct info
        if (!params->render_targets_.empty()) {
            for (auto & e : params->render_targets_) {
                if (e.info->cpp_extra.render_targets_info->target_index != UINT32_MAX) {
                    // TODO support more blending operations
                    RHIColorAttachmentBlendDesc blend {};
                    color_attachments.push_back({blend, e.info->cpp_extra.render_targets_info->format});
                } else {
                    depth_stencil = {
                        e.info->cpp_extra.render_targets_info->format
                    };
                }
            }
        }
        desc.color_attachments = color_attachments;
        desc.depth_stencil_attachment = depth_stencil;
        auto pipeline = RHI::Get().CreateGraphicsPipeline(
                desc, class_registry_->name.c_str()
        );
        if (!pipeline) {
            MI_LOG(MIInfraLogType::kError, "Failed to create graphics pipeline");
            return false;
        }
        graphics_pipeline_ = pipeline;
    }

    is_valid_ = true;

    // Remap bindings, so we can actually associate the shader parameters with RHI pipeline binding slots
    RemapResourceIndexToRHIResourceSlots();

    return true;
}

static RDGShaderLibrary * shader_library_instance_ptr;
RDGShaderLibrary &RDGShaderLibrary::Get() {
    if (shader_library_instance_ptr == nullptr) {
        shader_library_instance_ptr = new RDGShaderLibrary();
    }
    return *shader_library_instance_ptr;
}

void RDGShaderLibrary::DestroySingleton() {
    if (shader_library_instance_ptr) {
        delete shader_library_instance_ptr;
        shader_library_instance_ptr = {};
    }
}

RDGShaderLibrary::~RDGShaderLibrary() {}

void RDGShaderLibrary::Init() {
    // lalala
    MI_LOG(MIInfraLogType::kInfo, "Initializing RDGShaderLibrary");
}

void RDGShaderLibrary::RecompileUpdatedCachedShaders() {
    // Iterate over all shaders and check if they need to be recompiled
    std::vector<RDGShader*> shaders_to_recompile;
    for (auto & [type_hash, shader] : cached_shaders_) {
        if (shader->IsValid()) {
            // If the shader is valid, check for new hash value.
            auto old_hash = shader->GetShaderHash();
            auto new_hash = shader->ComputeShaderHash();
            if (old_hash != new_hash) {
                shaders_to_recompile.push_back(shader.get());
            }
        } else {
            // Invalid shaders always need to be recompiled
            shaders_to_recompile.push_back(shader.get());
        }
    }
    // Recompile all shaders that need to be recompiled
    // TODO parallize
    for (auto & shader : shaders_to_recompile) {
        shader->Recompile(shader->ini_);
    }
}


RDGShader *RDGShaderLibrary::GetShader(size_t type_hash, RDGShaderInitializationInfo ini) {
    struct {
        size_t type_hash;
        size_t ini_hash;
    } hash_data;
    hash_data.type_hash = type_hash;
    hash_data.ini_hash = ini.GetHash();
    size_t shader_hash = XXH64(&hash_data, sizeof(hash_data), 0);
    auto it = cached_shaders_.find(shader_hash);
    if (it == cached_shaders_.end()) {
        // Not cached, try to create a new shader
        auto reg = registered_shaders_.find(type_hash);
        if (reg == registered_shaders_.end()) {
            // The class does not exist.
            return nullptr;
        }
        auto new_shader = reg->second->Creator(reg->second.get(), ini);
        cached_shaders_[shader_hash].reset(new_shader);
        return new_shader;
    } else {
        return it->second.get();
    }
}

void RDGShaderLibrary::RegisterShaderClass(
    size_t type_hash,
    RDGShaderClassRegistry in_reg) {
    auto it = registered_shaders_.find(type_hash);
    if (it == registered_shaders_.end()) {
        auto reg = std::make_unique<RDGShaderClassRegistry>(in_reg);
        registered_shaders_[type_hash] = std::move(reg);
    } else {
        assert(false && "Double registration, this should never happen!");
    }
}

void RDGShaderLibrary::ReleaseCompiledShaders() {
    cached_shaders_.clear();
}



MI_NAMESPACE_END