/*
 * Created: 2025/3/8
 * Author:  hineven
 * See LICENSE for licensing.
 */
#include <ranges>
#include <utility>
#include <locale>

#include <xxhash.h>
#include "rdg/rdg_shader.h"

#include <codecvt>

#include "rhi/rhi.h"
#include "rhi/rhi_pipeline.h"
#include "core/infra.h"

#include "core/task.h"
#include "rhi/rhi_buffer.h"

MI_NAMESPACE_BEGIN
size_t RDGShaderInitializationInfo::GetHash() const {
    size_t final_hash = 0;
    // Order inreleavnt hashing.
#ifndef NDEBUG
    std::vector<uint64_t> hashes;
#endif
    for (const auto & macro : optional_macros) {
        auto curr_hash_value = XXH64(macro.c_str(), macro.size(), 12312321);
        final_hash ^= curr_hash_value;
#ifndef NDEBUG
        hashes.push_back(curr_hash_value);
#endif
    }
#ifndef NDEBUG
    std::sort(hashes.begin(), hashes.end());
    for (int i = 1; i < (int)hashes.size(); i++) {
        mi_assert(hashes[i] != hashes[i - 1], "Shader macro '{}' is duplicated. Must be a bug somewhere!", optional_macros[i]);
    }
#endif
    return final_hash;
}

bool RDGShaderParamStructInfo::CanBeRenderpass () const {
    for (auto & member : cpp_members) {
        if (member.type != RHIParamType::kRenderTarget) return false;
    }
    return true;
}

RDGShaderHash &RDGShaderHash::AddUnordered(const char *marker, uint64_t v) {
    uint64_t hash = XXH64(marker, strlen(marker), v);
    // Unordered. and can be duplicating.
    value += hash;
    return * this;
}


RDGShader::RDGShader (const RDGShaderClassRegistry * class_registry) : class_registry_(class_registry) {

}

RDGShader::~RDGShader () {

}

static std::string LoadFile(const std::string & path) {
    auto reader = GetInfra().RIO_Open(path, MIInfraResourceHintType::kShaderSource);
    if (!reader) {
        MI_LOG(MIInfraLogType::kError, "Failed to open resource: {}", path);
        return {};
    }
    auto size = reader->GetSize();
    std::string content(size, '\0');
    reader->ReadBlob(0, size, content.data());
    return content;
}

bool RDGShader::CheckShaderReflection(RHIShader * shader, const RDGShaderParamStructAndSizeInfo &info) {
    // Firstly, export uniform buffers from cpp shader param struct reflection
    TOneTimeLinearAllocator<> aloc;

    std::string entry = shader->GetEntryName();

    // Quick compare with hash values for the referenced structs
    bool passed_checking = true;
    auto & shader_reflected_uniform_buffers = shader->GetUniformBufferDesc();

    // Look for the autogenerated '$Globals' uniform buffer. (which should not be present)
    {
        bool flag = false;
        for (int j = 0; j < (int)shader_reflected_uniform_buffers.size(); ++j) {
            if (shader_reflected_uniform_buffers[j].name == "$Globals") {
                flag = true;
                break;
            }
        }
        if (flag) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' - Global uniform buffer is not supported. Use something like 'ConstantBuffer<UniformBufferStruct> UB;' instead.",
                   class_registry_->source_location, entry);
            passed_checking = false;
        }
    }

    if ((int)shader_reflected_uniform_buffers.size() > info.uniform_buffers_.size()) {
        // Shader is requesting for more uniform buffers than C++ has defined, find and log the missing ones
        for (const auto& shader_ub : shader_reflected_uniform_buffers) {
            bool found = false;
            for (const auto& cpp_ub : info.uniform_buffers_) {
                if (shader_ub.name == cpp_ub.info->name) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' - Uniform buffer '{}' is defined in shader but not found in C++",
                       class_registry_->source_location, entry, shader_ub.name);
                passed_checking = false;
            }
        }
    }

    // Find a resource in cpp reflection matching a specified name from shader reflection
    auto FindIndex = [&](std::span<RDGShaderParameterLocation> resources, const std::string & name) -> int {
        for (int i = 0; i < (int)resources.size(); ++i) {
            if (resources[i].info->name == name) {
                return i;
            }
        }
        return -1;
    };

    // Check and remap referenced uniform buffers
    cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer].resize(info.uniform_buffers_.size(), UINT32_MAX);
    for (auto const & [i, e] : std::views::enumerate(shader->GetUniformBufferDesc())) {
        // find corresponding uniform buffer in cpp reflection
        int cpp_ub_idx = FindIndex(info.uniform_buffers_, e.name);
        if (cpp_ub_idx == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}' - Uniform buffer '{}' is defined in shader but not found in C++",
                   class_registry_->source_location, e.name);
            passed_checking = false;
            // passed_checking = false;
        } else {
            // 25.5.19: Deep reflection is removed for uniform buffer structs.
            // It is up to the user for maintaining consistency between C++ and shaders.
            // Now we simply check if the sizes mismatches.
            if (e.array_size > 0) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' - Array '{}' of uniform buffers of length {} is not supported. (Any UB array is not supported).",
                       class_registry_->source_location, entry, e.name, e.array_size);
                passed_checking = false;
            }
            if (e.size != info.uniform_buffers_[cpp_ub_idx].size) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' - Uniform buffer '{}' has size mismatch between C++ and shader."
                       "Shader size: {}, C++ size: {}.",
                       class_registry_->source_location, entry, e.name, e.size, info.uniform_buffers_[cpp_ub_idx].size);
                passed_checking = false;
            }
        }
    }

    // Check storage buffers
    cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer].resize(info.storage_buffers_.size(), UINT32_MAX);
    for (const auto& sb : shader->GetStorageBufferDesc()) {
        int index = FindIndex(info.storage_buffers_, sb.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' uses storage buffer '{}' which is not defined among shader storage buffers",
                   class_registry_->source_location, entry, sb.name);
            passed_checking = false;
        } else {
            auto & member = *info.storage_buffers_[index].info;
            if ((member.access_flags & sb.access_flags) != sb.access_flags) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' defines '{}' as storage buffer but parameter access is not a super set of the shader reflected access flags."
                       "Shader flags: {}, Parameter flags: {}",
                       class_registry_->source_location, entry, sb.name, ToString(sb.access_flags), ToString(member.access_flags));
                passed_checking = false;
            }
        }
    }

    // Check UAV textures
    for (const auto& uav : shader->GetUAVDesc()) {
        int index = FindIndex(info.uavs_, uav.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' uses UAV texture '{}' which is not defined in shader parameters",
                   class_registry_->source_location, entry, uav.name);
            passed_checking = false;
        } else {
            auto & member = *info.uavs_[index].info;
            if (member.type != RHIParamType::kUAVTexture && member.type != RHIParamType::kUAVTextureArray) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' defines '{}' as UAV texture but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, entry, uav.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }
    // Check SRV textures
    for (const auto& srv : shader->GetSRVDesc()) {
        int index = FindIndex(info.srvs_, srv.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' uses SRV texture '{}' which is not defined in shader parameters",
                   class_registry_->source_location, entry, srv.name);
            passed_checking = false;
        } else {
            auto & member = *info.srvs_[index].info;
            if (member.type != RHIParamType::kSRVTexture && member.type != RHIParamType::kSRVTextureArray) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' defines '{}' as SRV texture but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, entry, srv.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check samplers
    for (const auto& sampler : shader->GetSamplerDesc()) {
        int index = FindIndex(info.samplers_, sampler.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' uses sampler '{}' which is not defined in shader parameters",
                   class_registry_->source_location, entry, sampler.name);
            passed_checking = false;
        } else {
            auto & member = *info.samplers_[index].info;
            if (member.type != RHIParamType::kSampler) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' defines '{}' as sampler but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, entry, sampler.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check acceleration structures
    for (const auto& as : shader->GetAccelerationStructureDesc()) {
        int index = FindIndex(info.acceleration_structures_, as.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                   "Shader '{}:{}' uses acceleration structure '{}' which is not defined in shader parameters",
                   class_registry_->source_location, entry, as.name);
            passed_checking = false;
        } else {
            auto & member = *info.acceleration_structures_[index].info;
            if (member.type != RHIParamType::kAccelerationStructure) {
                MI_LOG(MIInfraLogType::kWarning,
                       "Shader '{}:{}' defines '{}' as acceleration structure but parameter has incompatible type."
                       "Parameter type: {}",
                       class_registry_->source_location, entry, as.name, ToString(member.type));
                passed_checking = false;
            }
        }
    }

    // Check vertex attributes
    for (const auto& vb : shader->GetVertexInputDesc()) {
        int index = info.GetCppMemberIndex(vb.name);
        if (index == -1) {
            MI_LOG(MIInfraLogType::kWarning,
                "Shader '{}:{}' uses vertex attribute '{}' (location {}) which is not defined in shader parameters",
                class_registry_->source_location, entry, vb.name, vb.location);
            passed_checking = false;
            // Find the vertex attribute with corresponding location
            for (auto & member : info.cpp_members) {
                if (member.type == RHIParamType::kVertexAttribute
                && member.cpp_extra.vertex_attribute_info->attribute_index == vb.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "The declared vertex attribute with corresponding location is {}",
                        member.name);
                    break;
                }
            }
        } else {
            auto & member = info.cpp_members[index];
            if (member.type != RHIParamType::kVertexAttribute) {
                MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}:{}' defines '{}' as vertex attribute but parameter has incompatible type."
                        "Parameter type: {}",
                        class_registry_->source_location, entry, vb.name, ToString(member.type));
                passed_checking = false;
            } else {
                if (member.cpp_extra.vertex_attribute_info->attribute_index != vb.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}:{}' defines '{}' as vertex attribute but parameter has incompatible location."
                        "Parameter location: {}, Shader location: {}",
                        class_registry_->source_location, entry, vb.name, member.cpp_extra.vertex_attribute_info->attribute_index, vb.location);
                    passed_checking = false;
                }
                if (member.cpp_extra.vertex_attribute_info->format != vb.format) {
                    MI_LOG(MIInfraLogType::kWarning,
                            "Shader '{}:{}' defines '{}' as vertex attribute but parameter has incompatible format."
                            "Parameter format: {}, Shader format: {}",
                            class_registry_->source_location, entry, vb.name, ToString(member.cpp_extra.vertex_attribute_info->format), ToString(vb.format));
                    passed_checking = false;
                }
            }
        }
    }

    // Check fragment outputs (RenderTarget vs fragment output reflected from SPIR-V, check format compatibility)
    // (Names can be different, but the location and format must match)
    if (shader->GetFragmentOutputDesc().size()) {
        if (!info.render_targets_.size()) {
            MI_LOG(MIInfraLogType::kWarning, "Shader {} has fragment outputs but no render target is specified in C++.", class_registry_->source_location);
            passed_checking = false;
        } else {
            if (info.render_targets_.size() < shader->GetFragmentOutputDesc().size()) {
                MI_LOG(MIInfraLogType::kWarning,
                    "Shader {}:{} has {} fragment outputs but only {} is specified in C++, which is insufficient.",
                    class_registry_->source_location, entry, shader->GetFragmentOutputDesc().size(), info.render_targets_.size());
                passed_checking = false;
            }
        }
    }
    for (const auto & [i, output] : std::views::enumerate(shader->GetFragmentOutputDesc())) {
        int index = (int)i;
        if (index < info.render_targets_.size()) {
            auto & member = *info.render_targets_[index].info;
            if (member.type != RHIParamType::kRenderTarget) {
                MI_LOG(MIInfraLogType::kWarning,
                    "Shader '{}:{}' defines '{}' as fragment output but parameter has incompatible type."
                    "Parameter type: {}",
                    class_registry_->source_location, entry, output.name, ToString(member.type));
                passed_checking = false;
            } else {
                if (member.cpp_extra.render_targets_info->target_index != output.location) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}:{}' defines '{}' as fragment output but parameter has incompatible location."
                        "Parameter location: {}, Shader location: {}",
                        class_registry_->source_location, entry, output.name, member.cpp_extra.render_targets_info->target_index, output.location);
                    passed_checking = false;
                }
                if (!RHIIsOutputCompatiablePixelFormat(output.format, member.cpp_extra.render_targets_info->format)) {
                    MI_LOG(MIInfraLogType::kWarning,
                        "Shader '{}:{}' defines '{}' as fragment output but parameter has incompatible format."
                        "Parameter format: {}, Shader format: {}",
                        class_registry_->source_location, entry, output.name, ToString(member.cpp_extra.render_targets_info->format), ToString(output.format));
                    passed_checking = false;
                }
            }
        }
    }

    // TODO check immutable samplers, ...
    return passed_checking;
}

RHIPipelineResourceSlot RDGShader::ReflectResourceSlot(std::string_view name) const {
    return ReflectResourceSlot(CRC32(name.data(), name.size()));
}

RHIPipelineResourceSlot RDGShader::ReflectResourceSlot(uint32_t name_crc) const {
    if (class_registry_->type == RHIPipelineType::kCompute) return compute_pipeline_->ReflectResourceSlot(name_crc);
    if (class_registry_->type == RHIPipelineType::kGraphics) return graphics_pipeline_->ReflectResourceSlot(name_crc);
    if (class_registry_->type == RHIPipelineType::kRayTracing) return ray_tracing_pipeline_->ReflectResourceSlot(name_crc);
    assert(false && "Invalid shader type for RDGShader::ReflectResourceSlot");
    return {RHIPipelineResourceType::kMax, {}, {}};
}

bool RDGShader::HasResourceSlot(std::string_view name) const {
    return HasResourceSlot(CRC32(name.data(), name.size()));
}

bool RDGShader::HasResourceSlot(uint32_t name_crc) const {
    if (class_registry_->type == RHIPipelineType::kCompute) return compute_pipeline_->HasResourceSlot(name_crc);
    if (class_registry_->type == RHIPipelineType::kGraphics) return graphics_pipeline_->HasResourceSlot(name_crc);
    if (class_registry_->type == RHIPipelineType::kRayTracing) return ray_tracing_pipeline_->HasResourceSlot(name_crc);
    assert(false && "Invalid shader type for RDGShader::HasResourceSlot");
    return false;
}

std::vector<std::string> RDGShader::GetExtraCompilerOptions(const RDGShaderInitializationInfo & ini) const {
    std::vector<std::string> extra_options;
    for (const auto & extra_macro : ini.optional_macros) {
        extra_options.emplace_back("-D" + extra_macro);
    }
    // And some system macros based on shader type and other stuffs
    // Renderer environment
    extra_options.emplace_back("-DMI_RENDERER");
    // Shader class name
    extra_options.emplace_back(std::string("-D") + "MI_SHADER_" + class_registry_->name);
    // Shader type
    switch (class_registry_->type) {
        case RHIPipelineType::kGraphics:
            extra_options.emplace_back("-DMI_GRAPHICS_SHADER");
            break;
        case RHIPipelineType::kCompute:
            extra_options.emplace_back("-DMI_COMPUTE_SHADER");
            break;
        case RHIPipelineType::kRayTracing:
            extra_options.emplace_back("-DMI_RAY_TRACING_SHADER");
            break;
        default:
            assert(false);
    };
    return extra_options;
}

void RDGShader::RemapResourceIndexToRHIResourceSlots() {
    // Clear the previous bindings
    for (auto & e : cpp_resource_index_to_slot_) e.clear();
    assert(IsValid() && "Only with an assembled pipeline can we remap bindings");
    auto & info = *class_registry_->GetShaderParamStructInfo();
    RHIPipeline * pipeline = nullptr;
    if (class_registry_->type == RHIPipelineType::kGraphics) {
        pipeline = graphics_pipeline_.Raw();
    } else if (class_registry_->type == RHIPipelineType::kCompute) {
        pipeline = compute_pipeline_.Raw();
    } else if (class_registry_->type == RHIPipelineType::kRayTracing) {
        pipeline = ray_tracing_pipeline_.Raw();
    } else {
        assert(false);
        return;
    }
    auto FindSlotIndex = [&] <typename T> (const std::string & name, T & list) {
        for (int i = 0; i < (int)list.size(); ++i) {
            if (list[i].name == name) {
                return i;
            }
        }
        return -1;
    };
    // Remap uniform buffers
    {
        auto & ub = pipeline->GetUniformBufferDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer].resize(info.uniform_buffers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.uniform_buffers_)) {
            auto index = FindSlotIndex(e.info->name, ub);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUniformBuffer][i] = index;
            }
            // Potentially there are UBs declared in cpp but not present in shaders. Simply omit that case.
        }
    }
    // Remap storage buffers
    {
        auto & sb = pipeline->GetStorageBufferDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer].resize(info.storage_buffers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.storage_buffers_)) {
            auto index = FindSlotIndex(e.info->name, sb);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kStorageBuffer][i] = index;
            }
        }
    }
    // Remap uavs
    {
        auto & uavs = pipeline->GetUAVDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUAVTexture].resize(info.uavs_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.uavs_)) {
            auto index = FindSlotIndex(e.info->name, uavs);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kUAVTexture][i] = index;
            }
        }
    }
    // Remap srvs
    {
        auto & srvs = pipeline->GetSRVDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSRVTexture].resize(info.srvs_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.srvs_)) {
            auto index = FindSlotIndex(e.info->name, srvs);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSRVTexture][i] = index;
            }
        }
    }
    // Remap samplers
    {
        auto & samplers = pipeline->GetSamplerDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSampler].resize(info.samplers_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.samplers_)) {
            auto index = FindSlotIndex(e.info->name, samplers);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kSampler][i] = index;
            }
        }
    }
    // Remap as
    {
        auto & as = pipeline->GetAccelerationStructureDesc();
        cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kAccelerationStructure].resize(info.acceleration_structures_.size(), UINT32_MAX);
        for (const auto& [i, e] : std::views::enumerate(info.acceleration_structures_)) {
            auto index = FindSlotIndex(e.info->name, as);
            if (index != -1) {
                cpp_resource_index_to_slot_[(uint32_t)RHIParamType::kAccelerationStructure][i] = index;
            }
        }
    }
}



std::string RDGShader::LoadSource () const {
    // Firstly, load the source code from the source location
    auto source_code = LoadFile(class_registry_->source_location);
    return source_code;
}

// Localization support from C++ standard is incomplete. Resorting to codecvt
#pragma warning(push)
#pragma warning(disable : 4996)
static std::string wstring_to_utf8(std::wstring const& str)
{
    std::wstring_convert<std::conditional_t<
          sizeof(wchar_t) == 4,
          std::codecvt_utf8<wchar_t>,
          std::codecvt_utf8_utf16<wchar_t>>> converter;
    return converter.to_bytes(str);
}
#pragma warning(pop)

RDGShaderHash RDGShader::ComputeShaderHash() const {
    auto source_code = LoadSource();
    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "Failed to load shader source: {}", class_registry_->source_location);
        return {};
    }
    std::vector<std::string> extra_options = GetExtraCompilerOptions(ini_);
    // Insert default macros
    auto default_macros = class_registry_->GetShaderDefaultMacros();
    for (const auto & macro : default_macros) {
        extra_options.emplace_back("-D" + macro);
    }

    RDGShaderHash shader_hash {};

    if (class_registry_->type == RHIPipelineType::kCompute) {
        bool is_valid {false};
        auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
            class_registry_->source_location, extra_options, is_valid
        );
        if (is_valid) shader_hash.AddUnordered("ComputeShader", result);
        else MI_WARN("Failed to compute compute shader hash.");
    }

    if (class_registry_->type == RHIPipelineType::kGraphics) {
        if (!class_registry_->vertex_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("VertexShader", result);
            else MI_WARN("Failed to compute vertex shader hash.");
        }
        if (!class_registry_->fragment_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("FragmentShader", result);
            else MI_WARN("Failed to compute fragment shader hash.");
        }
    }

    if (class_registry_->type == RHIPipelineType::kRayTracing) {
        if (!class_registry_->raygen_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("RaygenShader", result);
            else MI_WARN("Failed to compute raygen shader hash.");
        }
        if (!class_registry_->closest_hit_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("ClosestHitShader", result);
            else MI_WARN("Failed to compute closest hit shader hash.");
        }
        if (!class_registry_->any_hit_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("AnyHitShader", result);
            else MI_WARN("Failed to compute any hit shader hash.");
        }
        if (!class_registry_->miss_entry_.empty()) {
            bool is_valid {false};
            auto result = GetInfra().GetShaderXXHashFromShaderResourcePath(
                class_registry_->source_location, extra_options, is_valid
            );
            if (is_valid) shader_hash.AddUnordered("MissShader", result);
            else MI_WARN("Failed to compute miss shader hash.");
        }
    }

    if (shader_hash.value == 0) {
        MI_LOG(MIInfraLogType::kError, "Failed to compute shader hash: {}", class_registry_->source_location);
        return {};
    }
    return shader_hash;
}

void RDGShader::UpdateOwnerForRHIResources() {
    if (shaders_.compute) shaders_.compute->UpdateOwner();
    if (shaders_.vertex) shaders_.vertex->UpdateOwner();
    if (shaders_.fragment) shaders_.fragment->UpdateOwner();

    if (shaders_.raygen) shaders_.raygen->UpdateOwner();
    if (shaders_.closest_hit) shaders_.closest_hit->UpdateOwner();
    if (shaders_.any_hit) shaders_.any_hit->UpdateOwner();
    if (shaders_.miss) shaders_.miss->UpdateOwner();
    if (shaders_.callable) shaders_.callable->UpdateOwner();

    if (sbt_buffer_) sbt_buffer_->UpdateOwner();

    if (graphics_pipeline_) graphics_pipeline_->UpdateOwner();
    if (compute_pipeline_) compute_pipeline_->UpdateOwner();
    if (ray_tracing_pipeline_) ray_tracing_pipeline_->UpdateOwner();
}


bool RDGShader::RecompileShaders(const std::string & source_code, const RDGShaderInitializationInfo & ini) {
    // Re-compile the shader
    shaders_ = {};
    shader_hash_.Reset();

    // Also reset the sbt buffer
    sbt_buffer_.SafeRelease();
    sbt_.clear();
    sbt_sections_ = {};

    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "RDGShader {}: Empty shader source: {}", class_registry_->name, class_registry_->source_location);
        return false;
    }
    // Reflect shader struct param info
    const RDGShaderParamStructAndSizeInfo & param_info = *class_registry_->GetShaderParamStructInfo();

    // Compile the shader and create RHI shaders
    std::string errmsg;
    auto absolute_path = GetInfra().TranslateResPathToFilePath(class_registry_->source_location);
    auto absolute_path_string = absolute_path.string();
    std::wstring source_location_wstr(absolute_path_string.begin(), absolute_path_string.end());

    // Stack macros
    std::vector<std::string> extra_options = GetExtraCompilerOptions(ini);
    // Insert default macros
    auto default_macros = class_registry_->GetShaderDefaultMacros();
    for (const auto & macro : default_macros) {
        extra_options.emplace_back("-D" + macro);
    }

    if(class_registry_->type == RHIPipelineType::kCompute) {
        uint64_t cs_hash = 0;
        std::wstring out_command;
        auto result = GetInfra().CompileHLSLToSPIRV(
                source_location_wstr.c_str(), std::string(class_registry_->compute_entry_), "cs_6_6",
                std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &cs_hash
        );
        if (result.empty()) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to compile compute shader for entry {}: {}", class_registry_->name, class_registry_->compute_entry_, errmsg);
            MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
            return false;
        }
        shader_hash_.AddUnordered("ComputeShader", cs_hash);
        // Create the compute shader
        auto bytecode_span = std::span(reinterpret_cast<const std::byte *>(result.data()), result.size() * sizeof(uint32_t));
        auto shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kCompute, class_registry_->compute_entry_,
                RHIShaderIRType::kSPIRV, bytecode_span
        );
        if (!shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Compute shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.compute = shader;
        shaders_.compute->SetSourceFilePath(class_registry_->source_location);
    }
    if(class_registry_->type == RHIPipelineType::kGraphics) {
        std::vector<uint32_t> vs_result, fs_result;
        // For graphics pipeline, we need to compile vertex and fragment shaders
        // First compile vertex shader
        {
            uint64_t vs_hash = 0;
            std::wstring out_command;
            vs_result = GetInfra().CompileHLSLToSPIRV(
                    source_location_wstr.c_str(), std::string(class_registry_->vertex_entry_), "vs_6_6",
                    std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &vs_hash
            );
            if (vs_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to compile vertex shader: {}", class_registry_->name, errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("VertexShader", vs_hash);
        }

        {
            uint64_t fs_hash = 0;
            std::wstring out_command;
            // Then compile fragment shader
            fs_result = GetInfra().CompileHLSLToSPIRV(
                    source_location_wstr.c_str(), std::string(class_registry_->fragment_entry_), "ps_6_6",
                    std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &fs_hash
            );
            if (fs_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to compile fragment shader: {}", class_registry_->name, errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("FragmentShader", fs_hash);
        }

        // Create the vertex shader
        auto vs_bytecode_span = std::span(reinterpret_cast<const std::byte*>(vs_result.data()), vs_result.size() * sizeof(uint32_t));
        auto vertex_shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kVertex, class_registry_->vertex_entry_,
                RHIShaderIRType::kSPIRV, vs_bytecode_span
        );
        if (!vertex_shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create vertex shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(vertex_shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Vertex shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.vertex = vertex_shader;
        shaders_.vertex->SetSourceFilePath(class_registry_->source_location);

        // Create the fragment shader
        auto fs_bytecode_span = std::span(reinterpret_cast<const std::byte*>(fs_result.data()), fs_result.size() * sizeof(uint32_t));
        auto fragment_shader = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kFragment, class_registry_->fragment_entry_,
                RHIShaderIRType::kSPIRV, fs_bytecode_span
        );
        if (!fragment_shader) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create fragment shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(fragment_shader.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Fragment shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.fragment = fragment_shader;
        shaders_.vertex->SetSourceFilePath(class_registry_->source_location);
    }

    if(class_registry_->type == RHIPipelineType::kRayTracing) {
        std::vector<uint32_t> raygen_result, chit_result, ahit_result, miss_result;
        // For graphics pipeline, we need to compile vertex and fragment shaders
        // First compile vertex shader
        {
            uint64_t raygen_hash = 0;
            std::wstring out_command;
            raygen_result = GetInfra().CompileHLSLToSPIRV(
                    source_location_wstr.c_str(), std::string(class_registry_->raygen_entry_), "lib_6_6",
                    std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &raygen_hash
            );
            if (raygen_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile raygen shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("RaygenShader", raygen_hash);
        }
        if (!class_registry_->closest_hit_entry_.empty()) {
            uint64_t chit_hash = 0;
            std::wstring out_command;
            chit_result = GetInfra().CompileHLSLToSPIRV(
                source_location_wstr.c_str(), std::string(class_registry_->closest_hit_entry_), "lib_6_6",
                std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &chit_hash
            );
            if (chit_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile closest hit shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("ClosestHitShader", chit_hash);
        }
        mi_check(!class_registry_->any_hit_entry_.empty(),
            "Any hit shader should never be empty."
            "Supply an any hit shader to make the pipeline valid on non-opaque geometries.");
        {
            uint64_t ahit_hash = 0;
            std::wstring out_command;
            ahit_result = GetInfra().CompileHLSLToSPIRV(
                source_location_wstr.c_str(), std::string(class_registry_->any_hit_entry_), "lib_6_6",
                std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &ahit_hash
            );
            if (ahit_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile any hit shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("AnyHitShader", ahit_hash);
        }
        {
            uint64_t miss_hash = 0;
            std::wstring out_command;
            miss_result = GetInfra().CompileHLSLToSPIRV(
                source_location_wstr.c_str(), std::string(class_registry_->miss_entry_), "lib_6_6",
                std::span(source_code.data(), source_code.size()), extra_options, errmsg, &out_command, &miss_hash
            );
            if (miss_result.empty()) {
                MI_LOG(MIInfraLogType::kError, "Failed to compile miss shader: {}", errmsg);
                MI_LOG(MIInfraLogType::kError, "Equivalent compile command: {}", wstring_to_utf8(out_command));
                return false;
            }
            shader_hash_.AddUnordered("MissShader", miss_hash);
        }
        shaders_.raygen = RHI::Get().CreateShader(
            RHIShaderFrequencyFlagBits::kRaygen, class_registry_->raygen_entry_,
            RHIShaderIRType::kSPIRV, std::span(reinterpret_cast<const std::byte*>(raygen_result.data()), raygen_result.size() * sizeof(uint32_t))
        );
        if (!shaders_.raygen) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create raygen shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(shaders_.raygen.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Raygen shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.raygen->SetSourceFilePath(class_registry_->source_location);
        if (!chit_result.empty()) {
            shaders_.closest_hit = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kClosestHit, class_registry_->closest_hit_entry_,
                RHIShaderIRType::kSPIRV, std::span(reinterpret_cast<const std::byte*>(chit_result.data()), chit_result.size() * sizeof(uint32_t))
            );
            if (!shaders_.closest_hit) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create closest hit shader", class_registry_->source_location);
                return false;
            }
            if (!CheckShaderReflection(shaders_.closest_hit.Raw(), param_info)) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Closest hit shader reflection check failed", class_registry_->source_location);
                return false;
            }
            shaders_.closest_hit->SetSourceFilePath(class_registry_->source_location);
        }
        {
            shaders_.any_hit = RHI::Get().CreateShader(
                RHIShaderFrequencyFlagBits::kAnyHit, class_registry_->any_hit_entry_,
                RHIShaderIRType::kSPIRV, std::span(reinterpret_cast<const std::byte*>(ahit_result.data()), ahit_result.size() * sizeof(uint32_t))
            );
            if (!shaders_.any_hit) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create any hit shader", class_registry_->source_location);
                return false;
            }
            if (!CheckShaderReflection(shaders_.any_hit.Raw(), param_info)) {
                MI_LOG(MIInfraLogType::kError, "RDGShader {}: Any hit shader reflection check failed", class_registry_->source_location);
                return false;
            }
            shaders_.any_hit->SetSourceFilePath(class_registry_->source_location);
        }
        shaders_.miss = RHI::Get().CreateShader(
            RHIShaderFrequencyFlagBits::kMiss, class_registry_->miss_entry_,
            RHIShaderIRType::kSPIRV, std::span(reinterpret_cast<const std::byte*>(miss_result.data()), miss_result.size() * sizeof(uint32_t))
        );
        if (!shaders_.miss) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Failed to create miss shader", class_registry_->source_location);
            return false;
        }
        if (!CheckShaderReflection(shaders_.miss.Raw(), param_info)) {
            MI_LOG(MIInfraLogType::kError, "RDGShader {}: Miss shader reflection check failed", class_registry_->source_location);
            return false;
        }
        shaders_.miss->SetSourceFilePath(class_registry_->source_location);
    }
    return true;
}

RDGShader::SBTBuffers RDGShader::GetSBTBuffers(RHICommandQueueGraphics & queue) {
    if (GetShaderClassRegistry()->type != RHIPipelineType::kRayTracing) {
        MI_LOG(MIInfraLogType::kError, "GetSBTBuffers called on non-ray tracing shader");
        return {};
    }
    // If the SBT buffer is not created, create it
    if (!sbt_buffer_) {
        // Create the SBT buffer
        sbt_buffer_ = RHI::Get().CreateBuffer(sbt_.size(),RHIBufferUsageFlagBits::kShaderBindingTable);
        if (!sbt_buffer_) {
            MI_LOG(MIInfraLogType::kError, "Failed to create SBT buffer for shader: {}", class_registry_->source_location);
            return {};
        }
        // Upload
        auto staging_buffer = RHI::Get().CreateBuffer(sbt_.size(), RHIBufferUsageFlagBits::kStaging);
        if (!staging_buffer) {
            MI_LOG(MIInfraLogType::kError, "Failed to create staging buffer for SBT buffer: {}", class_registry_->source_location);
            return {};
        }
        auto staging_data = staging_buffer->Map();
        memcpy(staging_data, sbt_.data(), sbt_.size());
        staging_buffer->Unmap();
        // Copy to the SBT buffer
        queue.CopyBuffer(staging_buffer->GetSpan(), sbt_buffer_->GetSpan());
        // Barrier to ensure the SBT buffer is ready for use
        queue.BufferBarrier(
            sbt_buffer_->GetSpan(), RHIPipelineStageFlagBits::kTransfer, RHIPipelineStageFlagBits::kRayTracing,
            RHIGPUAccessFlagBits::kTransferWrite, RHIGPUAccessFlagBits::kShaderBindingTableRead
        );
    }
    auto miss_stride = ray_tracing_pipeline_->GetMissSBTStride();
    auto hit_stride = ray_tracing_pipeline_->GetHitSBTStride();
    // The segments of th SBT buffer is fixed.
    return {
        sbt_buffer_->GetSpan(sbt_sections_.raygen.offset, sbt_sections_.raygen.size),
        sbt_buffer_->GetSpan(sbt_sections_.miss.offset, sbt_sections_.miss.size),
        sbt_buffer_->GetSpan(sbt_sections_.hit.offset, sbt_sections_.hit.size),
        miss_stride, hit_stride
    };
}

RDGShaderResourceAccess RDGShader::QueryShaderAccess(uint32_t crc32) const {
    auto param_struct_info = class_registry_->GetShaderParamStructInfo();
    auto cpp_index_it = param_struct_info->GetCppMemberIndex(crc32);
    if (cpp_index_it == -1) return {};
    if (!IsValid()) return {};
    if (!HasResourceSlot(crc32)) return {};
    auto pipeline_slot = ReflectResourceSlot(crc32);
    return {
        pipeline_slot.access_flags,
        GetStageFlagsFromShaderFrequencies(pipeline_slot.used_shaders)
    };
}


bool RDGShader::Recompile(RDGShaderInitializationInfo ini) {

    // Update owner to current thread
    UpdateOwnerForRHIResources();

    // Clear legacy resources
    graphics_pipeline_ = {};
    compute_pipeline_ = {};
    ray_tracing_pipeline_ = {};
    shaders_ = {};
    // Clear SBT related resources
    sbt_sections_ = {};
    sbt_ = {};
    sbt_buffer_.SafeRelease();

    is_valid_ = false;
    ini_ = ini;

    auto source_code = LoadSource();
    if (source_code.empty()) {
        MI_LOG(MIInfraLogType::kError, "Failed to load shader source: {}", class_registry_->source_location);
        return false;
    }
    if (!RecompileShaders(source_code, ini)) return false;


    auto pipeline_config = class_registry_->GetShaderPipelineConfig();

    // Assemble the pipeline
    if (class_registry_->type == RHIPipelineType::kCompute) {
        auto pipeline = RHI::Get().CreateComputePipeline(
            shaders_.compute.Raw(), class_registry_->name.c_str()
        );
        if (!pipeline) {
            MI_LOG(MIInfraLogType::kError, "Failed to create compute pipeline");
            return false;
        }
        compute_pipeline_ = pipeline;
    }
    if (class_registry_->type == RHIPipelineType::kGraphics) {
        RHIGraphicsPipelineDesc desc {};
        desc.stages.vertex_shader = shaders_.vertex.Raw();
        desc.stages.fragment_shader = shaders_.fragment.Raw();
        auto vertex_inputs = shaders_.vertex->GetVertexInputDesc();
        std::vector<RHIVertexInputBindingDesc> rhi_bindings;
        std::vector<RHIVertexInputAttributeDesc> rhi_attributes;
        // Gather vertex input configurations from shader param struct info
        auto params = class_registry_->GetShaderParamStructInfo();
        for (auto & e : params->cpp_members) {
            if (e.type == RHIParamType::kVertexBuffer) {
                auto input = e.cpp_extra.vertex_buffer_info;
                // TODO support more input rates
                rhi_bindings.emplace_back(input->index, input->stride, RHIVertexInputRateType::kVertex);
            }
            if (e.type == RHIParamType::kVertexAttribute) {
                auto attr = e.cpp_extra.vertex_attribute_info;
                rhi_attributes.emplace_back(attr->attribute_index, attr->buffer_index, attr->format, attr->offset);
            }
        }
        desc.vertex_input.vertex_buffers = rhi_bindings;
        desc.vertex_input.vertex_attributes = rhi_attributes;
        desc.topology = pipeline_config.topology;


        auto fragment_outputs = shaders_.fragment->GetFragmentOutputDesc();
        std::vector<RHIColorAttachmentDesc> color_attachments;
        RHIDepthStencilAttachmentDesc depth_stencil {};
        // Gather color attachment configurations from shader param struct info
        if (!params->render_targets_.empty()) {
            for (auto & e : params->render_targets_) {
                if (e.info->cpp_extra.render_targets_info->target_index != UINT32_MAX) {
                    RHIColorAttachmentBlendDesc blend {};
                    if (e.info->cpp_extra.render_targets_info->blending.blend_op != RHIBlendOpType::kMax) {
                        // TODO support more blending operations
                        blend.color_blend_op = e.info->cpp_extra.render_targets_info->blending.blend_op;
                        blend.src_color_blend_factor = e.info->cpp_extra.render_targets_info->blending.src_blend;
                        blend.dst_color_blend_factor = e.info->cpp_extra.render_targets_info->blending.dst_blend;
                        blend.alpha_blend_op = RHIBlendOpType::kBlendAdd;
                        blend.src_alpha_blend_factor = RHIBlendFactorType::kOne;
                        blend.dst_alpha_blend_factor = RHIBlendFactorType::kOneMinusSrcAlpha;
                    }
                    color_attachments.push_back({blend, e.info->cpp_extra.render_targets_info->format});
                } else {
                    // Enable depth testing
                    depth_stencil = {
                        e.info->cpp_extra.render_targets_info->format
                    };
                }
            }
        }
        desc.color_attachments = color_attachments;
        desc.depth_stencil_attachment = depth_stencil;
        if (depth_stencil.format != PixelFormatType::kUnknown) {
            desc.depth_stencil.depth_compare_op = pipeline_config.depth_compare_op;
            desc.depth_stencil.depth_test_enable = pipeline_config.depth_test_enabled;
            desc.depth_stencil.depth_write_enable = pipeline_config.depth_write_enabled;
        }
        auto pipeline = RHI::Get().CreateGraphicsPipeline(
                desc, class_registry_->name.c_str()
        );
        if (!pipeline) {
            MI_LOG(MIInfraLogType::kError, "Failed to create graphics pipeline");
            return false;
        }
        graphics_pipeline_ = pipeline;
    }
    if (class_registry_->type == RHIPipelineType::kRayTracing) {
        // Create the ray tracing pipeline
        RHIRayTracingPipelineDesc desc {};
        desc.shaders.push_back(shaders_.raygen.Raw());
        desc.shader_groups.push_back(RHIRayTracingShaderGroupDesc{RHIRayTracingShaderGroupType::kRayGeneration, 0});
        desc.shaders.push_back(shaders_.miss.Raw());
        desc.shader_groups.push_back(RHIRayTracingShaderGroupDesc{RHIRayTracingShaderGroupType::kMiss, 1});
        uint32_t closest_hit_idx = UINT32_MAX;
        uint32_t any_hit_idx = UINT32_MAX;
        uint32_t shader_idx_allocator = 2;
        if (shaders_.closest_hit && shaders_.closest_hit.IsValid()) {
            closest_hit_idx = shader_idx_allocator++;
            desc.shaders.push_back(shaders_.closest_hit.Raw());
        }
        if (shaders_.any_hit && shaders_.any_hit.IsValid()) {
            any_hit_idx = shader_idx_allocator++;
            desc.shaders.push_back(shaders_.any_hit.Raw());
        }
        desc.shader_groups.push_back(RHIRayTracingShaderGroupDesc{
            RHIRayTracingShaderGroupType::kTrianglesHitGroup,
            UINT32_MAX,
            closest_hit_idx,
            any_hit_idx
        });
        desc.max_recursion_depth = pipeline_config.ray_tracing.max_recursion_depth;
        auto pipeline = RHI::Get().CreateRayTracingPipeline(desc);
        if (!pipeline) {
            MI_LOG(MIInfraLogType::kError, "Failed to create ray tracing pipeline");
            return false;
        }
        ray_tracing_pipeline_ = pipeline;

        // Arranged in the order of raygen, miss, hit, ...
        auto base_alignment = ray_tracing_pipeline_->GetShaderGroupBaseAlignment();
        auto handle_size = ray_tracing_pipeline_->GetShaderGroupHandleSize();
        auto handle_size_aligned = RoundUp(
            handle_size,
            ray_tracing_pipeline_->GetShaderGroupHandleAlignment()
            );

        auto raygen_section_size = RoundUp(handle_size_aligned, base_alignment);
        auto miss_section_size = RoundUp(handle_size_aligned, base_alignment);
        auto hit_section_size = RoundUp(handle_size_aligned, base_alignment);

        auto all_size = raygen_section_size + miss_section_size + hit_section_size;
        sbt_.resize(all_size);

        // Get all handles into a temporary buffer first
        uint32_t handle_count = 3;
        std::vector<uint8_t> shader_handles(handle_count * handle_size);
        ray_tracing_pipeline_->GetShaderGroupHandles(0, handle_count, shader_handles.data());

        // Copy handles to the correct locations in the SBT
        // Order: raygen, miss, hit
        std::byte* sbt_data = sbt_.data();
        uint64_t current_offset = 0;

        // RayGen
        memcpy(sbt_data + current_offset, shader_handles.data(), handle_size);
        sbt_sections_.raygen = {current_offset, raygen_section_size};
        current_offset += raygen_section_size;

        // Miss
        memcpy(sbt_data + current_offset, shader_handles.data() + handle_size, handle_size);
        sbt_sections_.miss = {current_offset, miss_section_size};
        current_offset += miss_section_size;

        // Hit
        memcpy(sbt_data + current_offset, shader_handles.data() + handle_size * 2, handle_size);
        sbt_sections_.hit = {current_offset, hit_section_size};
    }

    // Set the valid flag to true before remapping resource indices
    is_valid_ = true;

    // Remap bindings, so we can actually associate the shader parameters with RHI pipeline binding slots
    RemapResourceIndexToRHIResourceSlots();

    return true;
}

static RDGShaderLibrary * shader_library_instance_ptr;
RDGShaderLibrary &RDGShaderLibrary::Get() {
    if (shader_library_instance_ptr == nullptr) {
        shader_library_instance_ptr = new RDGShaderLibrary();
    }
    return *shader_library_instance_ptr;
}

RDGShaderLibrary::~RDGShaderLibrary() {}

static bool ValidateMacroDecl (std::string macro_decl) {
    // Check for invalid characters in macro declaration
    int num_eq = 0;
    for (char c : macro_decl) {
        if (c == '=') num_eq ++;
        if (!isalnum(c) && c != '_' && c != '=') {
            MI_LOG(MIInfraLogType::kError, "Invalid character '{}' in macro declaration '{}'", c, macro_decl);
            return false;
        }
    }
    if (num_eq > 1) {
        MI_LOG(MIInfraLogType::kError, "Multiple '=' in macro declaration '{}'", macro_decl);
        return false;
    }
    // Macros should not start with a digit
    if (!macro_decl.empty() && isdigit(macro_decl[0])) {
        MI_LOG(MIInfraLogType::kError, "Macro declaration '{}' cannot start with a digit", macro_decl);
        return false;
    }
    // Macros should not be empty
    if (macro_decl.empty()) {
        MI_LOG(MIInfraLogType::kError, "Macro declaration cannot be empty");
        return false;
    }
    return true;
}

static uint64_t HashCompiledShader (uint64_t type_hash, const RDGShaderInitializationInfo & ini) {
    struct {
        uint64_t type_hash;
        uint64_t ini_hash;
    } hash_data;
    hash_data.type_hash = type_hash;
    hash_data.ini_hash = ini.GetHash();
    uint64_t shader_hash = XXH64(&hash_data, sizeof(hash_data), 0);
    return shader_hash;
}

void RDGShaderLibrary::Init() {
    MI_LOG(MIInfraLogType::kInfo, "Initializing RDGShaderLibrary");

    // Enumerate all registered shaders, call their parameter structs' InitShaderParamStructInfo
    // in case two or more shaders share the same parameter struct and found a race condition
    // in the following multi-threading compilation.
    for (const auto & shader_class : registered_shader_classes_) {
        shader_class.second->InitShaderParamStructInfo();
    }

    // Pre-compile shaders. Cache them to prevent sudden lagging when switching
    // rendering operations.
    struct ShaderToCompile {
        std::vector<std::string> macro_decls;
        RDGShaderClassRegistry * shader_class;
    };

    std::vector<ShaderToCompile> shaders_to_compile;
    std::function<void(const std::vector<std::pair<std::string, std::vector<std::string>>> & macro_decls,
        RDGShaderClassRegistry * shader_class, std::vector<std::string> & generated_macro_decls,
        int curr_macro_decl_index)> GenerateShaderPermutations = [&] (
        const std::vector<std::pair<std::string, std::vector<std::string>>> & macro_decls,
        RDGShaderClassRegistry * shader_class, std::vector<std::string> & generated_macro_decls,
        int curr_macro_decl_index) {
        if (curr_macro_decl_index >= (int)macro_decls.size()) {
            // We have generated a full permutation, add it to the list
            shaders_to_compile.push_back({generated_macro_decls, shader_class});
            return;
        }
        // Iterate over all possible values for the current macro declaration
        const auto & macro_decl = macro_decls[curr_macro_decl_index];
        if (macro_decl.second[0].empty()) {
            // Flag macro
            // Either include or exclude
            generated_macro_decls.push_back(macro_decl.first);
            GenerateShaderPermutations(macro_decls, shader_class, generated_macro_decls, curr_macro_decl_index + 1);
            generated_macro_decls.pop_back();
            GenerateShaderPermutations(macro_decls, shader_class, generated_macro_decls, curr_macro_decl_index + 1);
        } else {
            // Value macro
            // Enumeare all possible values
            for (const auto & e : macro_decl.second) {
                generated_macro_decls.push_back(macro_decl.first + "=" + e);
                GenerateShaderPermutations(macro_decls, shader_class, generated_macro_decls, curr_macro_decl_index + 1);
                generated_macro_decls.pop_back();
            }
        }
    };

    for (const auto & shader_class : registered_shader_classes_) {
        auto optional_macros = shader_class.second->GetShaderOptionalMacros();
        // Find all possible permutations for the optional macros
        std::map<std::string, std::vector<std::string>> macro_values;
        for (auto optional_macro : optional_macros) {
            if (!ValidateMacroDecl(optional_macro)) {
                MI_WARN("Invalid optional macro declaration '{}' for shader {}, skipping", optional_macro, shader_class.second->name);
                continue ;
            }
            if (optional_macro.find_first_of('=') != std::string::npos) {
                // Split the macro declaration into name and value
                auto pos = optional_macro.find('=');
                std::string macro_name = optional_macro.substr(0, pos);
                std::string macro_value = optional_macro.substr(pos + 1);
                macro_values[macro_name].push_back(macro_value);
            } else {
                // No value, just a flag
                macro_values[optional_macro].push_back("");
            }
        }
        // Unique macro values
        for (auto & e : macro_values) {
            auto & values = e.second;
            std::sort(values.begin(), values.end());
            values.erase(std::unique(values.begin(), values.end()), values.end());
            if (values.size() > 1 && values[0].empty()) {
                // If the first value is empty, and there are more values, the macro seems to be ill
                // defined. We should warn about it.
                std::string value_list;
                for (auto v : values) {
                    if (!v.empty()) {
                        if (!value_list.empty()) value_list += ", ";
                        value_list += v;
                    }
                }
                MI_WARN("Shader {} has optional macro '{}' with empty value, but also has other values ({}). "
                        "Dropping the flag behavior of the macro.",
                        shader_class.second->name, e.first, value_list);
                // The macro will not be used as a flag, but as a value.
                values.erase(values.begin());
            }
        }
        std::vector<std::pair<std::string, std::vector<std::string>>> macro_decls;
        for (auto e : macro_values) {
            // Convert the map to a vector of pairs
            macro_decls.emplace_back(e.first, e.second);
        }
        std::vector<std::string> generated_macro_decls;
        // Generate all combinations of macro values
        GenerateShaderPermutations(macro_decls, shader_class.second.get(), generated_macro_decls, 0);
    }

    MI_INFO("ShaderLibrary: Gathered {} shader permutations to compile.", shaders_to_compile.size());

    std::vector<TaskRef> compile_tasks;
    compile_tasks.reserve(shaders_to_compile.size());
    std::mutex cache_mutex; // Ensure thread safety when updating the cache

    for (auto & shader : shaders_to_compile) {
        auto task = TaskGraph::Get().CreateSimpleTask([this, &shader, &cache_mutex]() {
            RDGShaderInitializationInfo ini;
            ini.optional_macros = shader.macro_decls;
            auto new_shader = shader.shader_class->Creator(shader.shader_class);
            if (!new_shader->Recompile(ini)) {
                std::string macro_decl;
                for (const auto & macro : shader.macro_decls) {
                    if (!macro_decl.empty()) macro_decl += ", ";
                    macro_decl += macro;
                }
                MI_LOG(MIInfraLogType::kError, "Failed to compile shader {} with optional macros: {}",
                       shader.shader_class->name, macro_decl);
            }
            {
                std::lock_guard<std::mutex> lock(cache_mutex);
                cached_shaders_[HashCompiledShader(shader.shader_class->type_hash, ini)].reset(new_shader);
            }
        });
        compile_tasks.push_back(task);
    }

    TaskGraph::Get().WaitForTasks(compile_tasks);
    // Transfer the ownership of underlying RHI resources to the render thread (current thread)
    for (auto & shader : cached_shaders_) {
        shader.second->UpdateOwnerForRHIResources();
    }
}

void RDGShaderLibrary::Deinit() {
    cached_shaders_.clear();
}


void RDGShaderLibrary::RecompileUpdatedCachedShaders() {
    // Iterate over all shaders and check if they need to be recompiled
    std::vector<RDGShader*> shaders_to_recompile;
    for (auto & [type_hash, shader] : cached_shaders_) {
        if (shader->IsValid()) {
            // If the shader is valid, check for new hash value.
            auto old_hash = shader->GetShaderHash();
            auto new_hash = shader->ComputeShaderHash();
            if (old_hash != new_hash) {
                shaders_to_recompile.push_back(shader.get());
            }
        } else {
            // Invalid shaders always need to be recompiled
            shaders_to_recompile.push_back(shader.get());
        }
    }
    // Recompile all shaders that need to be recompiled
    auto tasks = TaskGraph::Get().ForEach(shaders_to_recompile, [](RDGShader * shader) {
        shader->Recompile(shader->ini_);
    });

    TaskGraph::Get().WaitForTasks(tasks);

    for (auto &shader: shaders_to_recompile) {
        shader->UpdateOwnerForRHIResources();
    }
    MI_INFO("RDGShaderLibrary: {} shaders recompiled.", shaders_to_recompile.size());
}


RDGShader *RDGShaderLibrary::GetShader(size_t type_hash, RDGShaderInitializationInfo ini) {
    size_t shader_hash = HashCompiledShader(type_hash, ini);
    auto it = cached_shaders_.find(shader_hash);
    if (it == cached_shaders_.end()) {
        // Not cached, try to create a new shader
        auto reg = registered_shader_classes_.find(type_hash);
        if (reg == registered_shader_classes_.end()) {
            // The class does not exist.
            return nullptr;
        }
        MI_INFO("Missing shader {} with hash {}. Creating it.", reg->second->name, shader_hash);
        auto new_shader = reg->second->Creator(reg->second.get());
        if (!new_shader->Recompile(ini)) {
            MI_LOG(MIInfraLogType::kError, "Failed to compile shader {} with hash {}",
                   reg->second->name, shader_hash);
            return nullptr;
        }
        cached_shaders_[shader_hash].reset(new_shader);
        return new_shader;
    } else {
        return it->second.get();
    }
}

void RDGShaderLibrary::RegisterShaderClass(
    size_t type_hash,
    RDGShaderClassRegistry in_reg) {
    auto it = registered_shader_classes_.find(type_hash);
    if (it == registered_shader_classes_.end()) {
        auto reg = std::make_unique<RDGShaderClassRegistry>(in_reg);
        registered_shader_classes_[type_hash] = std::move(reg);
    } else {
        assert(false && "Double registration, this should never happen!");
    }
}

void RDGShaderLibrary::ReleaseCompiledShaders() {
    cached_shaders_.clear();
}



MI_NAMESPACE_END