/*
 * Created: 2024/7/13
 * Author:  hineven
 * See LICENSE for licensing.
 */

#ifndef MI_VK_CMD_EXEC_H
#define MI_VK_CMD_EXEC_H

#include "rhi/rhi_cmd.h"
#include "../rhi_cmd_exec.h"
#include "rhi/rhi_pipeline.h"
#include "vk_constants.h"

MI_NAMESPACE_BEGIN

class VulkanBuffer;
class VulkanGraphicsPipeline;
class VulkanComputePipeline;

// Command executor translating recoreded commands into Vulkan API calls
// Public functions are only invoked by the RHI thread
class VulkanCommandExecutor : public RHICommandExecutorInterface {
public:
    VulkanCommandExecutor() ;
    virtual ~VulkanCommandExecutor() override ;

    void RHICopyBuffer(RHICommandQueueBase * cmd, RHICommandCopyBuffer * copy_buffer) override ;
    void RHICopyTexture(RHICommandQueueBase * cmd, RHICommandCopyTexture * copy_texture) override ;
    void RHIDrawPrimitive(RHICommandQueueBase * cmd, RHICommandDrawPrimitive * draw_primitive) override ;
    void RHIDrawIndexedPrimitive(RHICommandQueueBase * cmd, RHICommandDrawIndexedPrimitive * draw_indexed_primitive) override ;
    void RHIDispatch(RHICommandQueueBase * cmd, RHICommandDispatch * dispatch) override ;
    void RHIBindGraphicsPipeline(RHICommandQueueBase * cmd, RHICommandBindGraphicsPipeline * bind_graphics_pipeline) override ;
    void RHIBindComputePipeline(RHICommandQueueBase * cmd, RHICommandBindComputePipeline * bind_compute_pipeline) override ;
    void RHIBindPipelineParameters(RHICommandQueueBase * cmd, RHICommandBindPipelineParameters * bind_pipeline_parameters) override ;
    void RHIBindVertexBuffer(RHICommandQueueBase * cmd, RHICommandBindVertexBuffer * bind_vertex_buffer) override ;
    void RHIFrameEnd(RHICommandQueueBase * cmd, RHICommandFrameEnd * frame_end) override ;

    void RHISubmitCommandBuffer (RHICommandQueueBase * buffer, bool block_until_device_completion) override ;
protected:


    void FlushBindPointDescriptorWrites (RHICommandQueueBase *, RHIBindPointType, vk::PipelineStageFlags use_stages) ;

    void Initialize_RHIThread () ;
    void Destroy_RHIThread () ;

    typedef std::span<vk::WriteDescriptorSet> DescriptorWrites;

    struct CommandQueueState {
        // Each command queue has its own command pool and 1 single command buffer recording
        vk::CommandPool cmd_pool {};
        vk::CommandBuffer cmd {};
        // Can bind up to 8 vertex buffers
        RHIBufferSpan bound_vertex_buffers[8] {};
        struct BindPoints {
            // Bindless table buffer
            std::unique_ptr<VulkanBuffer> bindless_table_buffer {};
            // Bindless table allocation offset
            uint32_t bindless_table_top;

            // Bound private descriptor set (allocated from the descriptor pool)
            vk::DescriptorSet bound_private_set {};
            // Store a pointer to the currently bound pipeline
            RHIPipeline * bound_pipeline {};
            template<typename T>
            inline T * As() {
                return static_cast<T *>(bound_pipeline);
            }
            struct ParameterTable {
                std::vector<RHIPipelineParameterBufferDesc> uniforms;
                std::vector<RHIPipelineParameterBufferDesc> storages;
                std::vector<RHIPipelineParameterTextureDesc> uavs;
                std::vector<RHIPipelineParameterTextureDesc> srvs;
                std::vector<RHIPipelineParameterResourceDesc> samplers;
                std::vector<RHIPipelineParameterResourceDesc> acceleration_structures;
                std::vector<RHIPipelineBindlessResourceDesc> bindless_resources;
                std::span<const std::byte> push_constants;

                // Clear parameter table and launch descriptor writes.
                // Note: Only image layout transition barriers are placed automatically.
                // You need to explicitly place memory / execution barriers.
                // Note(2): RDG handles these barriers.
                // @param use_stages: The stages that currently tabled resources will be used in.
                // @return: The descriptor writes and btb_data generated by this function.
                DescriptorWrites FlushDescriptorWrites (
                        RHICommandQueueBase * cmd, vk::Device device,
                        vk::DescriptorSet descriptor_set, std::span<std::uint32_t> btb_data,
                        vk::CommandBuffer cmdb, vk::PipelineStageFlags use_stages
                );
                // Merge incoming table
                void Merge (const RHIBindPipelineParametersDesc * desc);
            } parameter_table;


        } points[(uint32_t)RHIBindPointType::kMax];

        vk::DescriptorPool descriptor_pool {};

        // Should be initialize & destroyed on the RHI thread only
        void Init (RHICommandQueueType type) ;
        void Destroy () ;
        // Clear the command buffer and descriptor sets.
        // @param return_resources_to_system: If true, the resources allocated by the command buffer and descriptor sets
        void Clear (bool return_resources_to_system) ;
    };
    struct {
        CommandQueueState states[2];
        int state_index {};
        inline CommandQueueState & Current() {
            return states[state_index];
        }
    } state_chains_[(uint32_t)RHICommandQueueType::kMax];
};

MI_NAMESPACE_END
#endif //MI_VK_CMD_EXEC_H
