#ifndef SHARED_HASH_GRID_CACHE_HLSL
#define SHARED_HASH_GRID_CACHE_HLSL

#define HASHGRIDS_TILE_CELL_WIDTH 8
#define HASHGRIDS_MAX_NUM_ENTRIES_SEARCHED_PER_BUCKET 8
#define HASHGRIDS_TILE_CELL_MIP_OFFSET_0 0
#define HASHGRIDS_TILE_CELL_MIP_OFFSET_1 (HASHGRIDS_TILE_CELL_WIDTH * HASHGRIDS_TILE_CELL_WIDTH)
#define HASHGRIDS_TILE_CELL_MIP_OFFSET_2 (HASHGRIDS_TILE_CELL_MIP_OFFSET_1 + (HASHGRIDS_TILE_CELL_MIP_OFFSET_1 / 4))
#define HASHGRIDS_TILE_CELL_MIP_OFFSET_3 (HASHGRIDS_TILE_CELL_MIP_OFFSET_2 + (HASHGRIDS_TILE_CELL_MIP_OFFSET_1 / 16))
#define HASHGRIDS_NUM_CELLS_PER_TILE (HASHGRIDS_TILE_CELL_MIP_OFFSET_3 + 1)

#endif